version: 2

resources:
  build: &build
    docker:
      - image: circleci/ruby:2.4.3-stretch
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace: { at: /tmp/workspace }
      - run: if [ -n "${load_image}" ]; then zcat /tmp/workspace/${load_image}.tar.gz | docker load; fi
      - run: docker build -t minimum2scp/${CIRCLE_JOB}:latest ${CIRCLE_JOB}
      - run: zcat /tmp/workspace/rspec-runner.tar.gz | docker load
      - run:
          name: Setup rspec-runner environment variables and volumes
          command: |
            printenv | sort | grep -Ev '^(DOCKER_CERT_PATH|CIRCLE_BUILD_TOKEN)=' | grep -E '^(CI=|CIRCLECI=|CIRCLE_|DOCKER_)' > .circleci/env
            echo "DOCKER_CERT_PATH=/data/$(basename ${DOCKER_CERT_PATH})" >> .circleci/env
            docker volume create data
            docker create --name cfg -v data:/data minimum2scp/rspec-runner:ci
            docker cp ${DOCKER_CERT_PATH} cfg:/data
            docker rm cfg
      - run: docker run --rm -t --env-file .circleci/env -v data:/data minimum2scp/rspec-runner:ci bundle exec rake spec:${CIRCLE_JOB}
      - run:
          name: Save image to workspace
          command: |
            case "${CIRCLE_JOB}" in
              baseimage|baseimage-*|ruby)
                echo "Saving image minimum2scp/${CIRCLE_JOB}:latest to /tmp/${CIRCLE_JOB}.tar.gz"
                docker save minimum2scp/${CIRCLE_JOB}:latest | gzip -c - > /tmp/${CIRCLE_JOB}.tar.gz
                ;;
              *)
                echo "Skipped to save image minimum2scp/${CIRCLE_JOB}:latest, creating /tmp/${CIRCLE_JOB}.tar.gz as empty file"
                : > /tmp/${CIRCLE_JOB}.tar.gz
                ;;
            esac
      - persist_to_workspace:
          root: /tmp
          paths: [ "*.tar.gz" ]

jobs:
  rspec-runner:
    docker:
      - image: circleci/ruby:2.4.3-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t minimum2scp/rspec-runner:ci -f .circleci/rspec-runner/Dockerfile .
      - run: docker save minimum2scp/rspec-runner:ci | gzip -c - > /tmp/rspec-runner.tar.gz
      - persist_to_workspace:
          root: /tmp
          paths: [rspec-runner.tar.gz]
  baseimage:
    <<: *build
  nodejs:
    <<: *build
    environment:
      load_image: baseimage
  ruby:
    <<: *build
    environment:
      load_image: baseimage
  fluentd-ui:
    <<: *build
    environment:
      load_image: ruby
  ruby-full:
    <<: *build
    environment:
      load_image: ruby
  rails5:
    <<: *build
    environment:
      load_image: ruby
  baseimage-stretch:
    <<: *build
  ruby-stretch:
    <<: *build
    environment:
      load_image: baseimage-stretch
  baseimage-jessie:
    <<: *build
  ruby-jessie:
    <<: *build
    environment:
      load_image: baseimage-jessie
  baseimage-wheezy:
    <<: *build
  ruby-wheezy:
    <<: *build
    environment:
      load_image: baseimage-wheezy

workflows:
  version: 2
  build_and_test:
    jobs:
      - rspec-runner
      - baseimage:
          requires: [rspec-runner]
      - nodejs:
          requires: [rspec-runner, baseimage]
      - ruby:
          requires: [rspec-runner, baseimage]
      - fluentd-ui:
          requires: [rspec-runner, ruby]
      - ruby-full:
          requires: [rspec-runner, ruby]
      - rails5:
          requires: [rspec-runner, ruby]
      - baseimage-stretch:
          requires: [rspec-runner]
      - ruby-stretch:
          requires: [rspec-runner, baseimage-stretch]
      - baseimage-jessie:
          requires: [rspec-runner]
      - ruby-jessie:
          requires: [rspec-runner, baseimage-jessie]
      - baseimage-wheezy:
          requires: [rspec-runner]
      - ruby-wheezy:
          requires: [rspec-runner, baseimage-wheezy]
 
