version: 2
jobs:
  build:
    working_directory: /tmp/dockerfiles

    docker:
      - image: circleci/ruby:2.4.1

    steps:
      - run:
          name: Check ruby version
          command: |
            set -x
            ruby -v
            gem env
            bundle version

      - checkout

      - setup_remote_docker

      - run:
          name: Check docker version
          command: |
            set -x
            docker version
            docker info

      - run:
          name: Install java
          command: |
            set -x
            echo "deb http://deb.debian.org/debian jessie-backports main" | sudo tee /etc/apt/sources.list.d/jessie-backports.list
            sudo apt-get update
            sudo apt-get install openjdk-8-jre-headless -t jessie-backports -y --no-install-recommends

      - run:
          name: Install digdag
          command: |
            set -x
            sudo curl -o /usr/local/bin/digdag -L "https://dl.digdag.io/digdag-latest"
            sudo chmod +x /usr/local/bin/digdag

      - run: digdag --version
      - run: digdag check
      - run: digdag run ci-build.dig --rerun

      - run:
          name: Setup rspec-runner environment variables and volumes
          command: |
            printenv | sort | grep -Ev '^(DOCKER_CERT_PATH|CIRCLE_BUILD_TOKEN)=' | grep -E '^(CI=|CIRCLECI=|CIRCLE_|DOCKER_)' > .circleci/env
            echo "DOCKER_CERT_PATH=/data/$(basename ${DOCKER_CERT_PATH})" >> .circleci/env
            docker volume create data
            docker create --name cfg -v data:/data minimum2scp/rspec-runner:ci
            docker cp ${DOCKER_CERT_PATH} cfg:/data
            docker rm cfg

      - run: docker run --rm -t --env-file .circleci/env -v data:/data minimum2scp/rspec-runner:ci bundle exec rspec

      - store_artifacts:
          path: .circleci/log/
          destination: log

